#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 20 15:48:22 2019

@author: tomas
"""

import math

"""
Primer trabajo del curso
Tema 2
"""
# Poner aqui el nombre del estudiante autor del trabajo
NOMBRE_ESTUDIANTE = "Sergio Jimeno"


# susituir pass por tu codigo
def nota(trabajos, parcial1, parcial2):
    return (trabajos*0.3+parcial1*0.35+parcial2*0.35)

def comprobar_nota():
    print ("Notas: ")
    # Esto debe dar 5.0
    print("Nota (debe dar 5.0) =", nota(5, 5, 5))
    # Esto debe dar aproximadamente 7.0
    print("Nota (debe dar 7.0) =", nota(0, 10, 10))
    # poner mas comprobaciones ...
    print ("mas comprobaciones: ")
    print("nota (debe de dar 4.65) =", nota(5, 1, 8))
    print("nota (debe de dar 5.1) =", nota(3, 4, 8))
    print("nota (debe de dar 6.25) =", nota(8, 7, 4))


# susituir pass por tu codigo
def area_triangulo(a, b, c):
    s=1/2*(a+b+c)
    return (math.sqrt(s*(s-a)*(s-b)*(s-c)))

def comprobar_area_triangulo():
    print ("Areas: ")
    # Esto debe dar aproximadamente 0.5
    print("Area (debe dar 0.5) =", area_triangulo(1, 1, math.sqrt(2)))
    # Esto debe dar aproximadamente 0.0
    print("Area (debe dar 0.0) =", area_triangulo(1, 1, 2))
    # poner mas comprobaciones ...
    print("mas comprobaciones: ")
    print("Area (debe de dar 1.0) =", area_triangulo(1, 2, math.sqrt(5)))
    print("Area (debe de dar 1.5) =", area_triangulo(1, 3, math.sqrt(10)))
    print("Area (debe de dar 5.0) =", area_triangulo(5, 2, math.sqrt(29)))

print('## Trabajo 02 de la asignatura de informatica ##')
print('ESTUDIANTE :', NOMBRE_ESTUDIANTE)

# Ejecutar las comprobaciones
comprobar_nota()
comprobar_area_triangulo()

